services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: craftyprep-prod
    restart: unless-stopped
    networks:
      - traefik_demosrv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.craftyprep.rule=Host(`craftyprep.demosrv.uk`)"
      - "traefik.http.routers.craftyprep.entrypoints=websecure"
      - "traefik.http.routers.craftyprep.tls.certresolver=myresolver"
      - "traefik.http.services.craftyprep.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik_demosrv:
    external: true
