services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: craftyprep-dev
    ports:
      - "5173:5173" # Vite dev server
      - "9229:9229" # Node.js debugger
    volumes:
      # Mount source code for hot-reload
      - .:/app
      # Use named volume for node_modules (don't override)
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - dev-network

volumes:
  node_modules:

networks:
  dev-network:
    driver: bridge
