name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./src

      - name: Lint
        run: npm run lint
        working-directory: ./src

      - name: Type check
        run: npm run typecheck
        working-directory: ./src

      - name: Unit tests
        run: npm test
        working-directory: ./src

      - name: Unit tests with coverage
        run: npm run test:coverage
        working-directory: ./src

      - name: Security audit
        run: npm audit --audit-level=moderate
        working-directory: ./src
        continue-on-error: true

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        working-directory: ./src

      - name: E2E tests
        run: npm run test:e2e
        working-directory: ./src

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: src/playwright-report/
          retention-days: 30
